// Chess Tournament Manager 2.0
// Notation sheets, reports, backups, CSV, reset, and sample tools.

function notationBlank(){
  nWhite.value='';nWhiteSchool.value='';nBlack.value='';nBlackSchool.value='';nRound.value='';nBoard.value='';nDate.value=state.settings.date||'';nResult.value='';
  buildNotationGrid([]);
}
function notationSample(){
  nWhite.value='Miguel Santos';nWhiteSchool.value='Taysan Senior High School';nBlack.value='Andrea Reyes';nBlackSchool.value='Batangas National High School';nRound.value='1';nBoard.value='1';nDate.value=state.settings.date||'';nResult.value='1-0';
  const moves=['e4','e5','Nf3','Nc6','Bb5','a6','Ba4','Nf6','O-O','Be7','Re1','b5','Bb3','d6','c3','O-O','h3','Nb8','d4','Nbd7','c4','c6','cxb5','axb5','Nc3','Bb7','Bg5','b4','Nb1','h6','Bh4','c5','dxe5','Nxe4','Bxe7','Qxe7','exd6','Qf6','Nbd2','Nxd6'];
  buildNotationGrid(moves);
}
function buildNotationGrid(moves=[]){
  let out='<div class="head">#</div><div class="head">WHITE</div><div class="head">BLACK</div>';
  for(let i=1;i<=60;i++){out+=`<div style="text-align:center">${i}.</div><div>${esc(moves[(i-1)*2]||'')}</div><div>${esc(moves[(i-1)*2+1]||'')}</div>`;}
  notationGrid.innerHTML=out;
}
function renderReports(){
  const st=state.settings.mode==='team'?teamStandings():standings(), s=state.settings;
  let roundsHtml=state.rounds.map(r=>`<h4>Round ${r.number}</h4><table><thead><tr><th>Board</th><th>White</th><th>Result</th><th>Black</th></tr></thead><tbody>${r.games.map(g=>`<tr><td>${g.board}</td><td>${esc(playerDisplay(getPlayer(g.white)))}</td><td>${g.bye?'BYE':esc(g.result||'—')}</td><td>${g.bye?'—':esc(playerDisplay(getPlayer(g.black)))}</td></tr>`).join('')}</tbody></table>`).join('');
  reportBox.innerHTML=`<div style="text-align:center"><h2 style="margin-bottom:4px">${esc(s.name)}</h2><div><b>${esc(s.school||'')}</b></div><div>${esc(s.venue)} • ${esc(s.date)} • ${esc(s.timeControl)}</div><div>Chief Arbiter: ${esc(s.chiefArbiter||'—')}</div><div>Tournament Director (TD): ${esc(s.tournamentDirector||'—')}</div></div><hr style="border-color:#aaa">
  <h3>Final / Current Standings</h3>${state.settings.mode==='team'
    ? `<table><thead><tr><th>Rank</th><th>Team</th><th>Match Pts</th><th>Board Pts</th><th>Wins</th></tr></thead><tbody>${st.map((t,i)=>`<tr><td>${i+1}</td><td>${esc(t.name)}</td><td>${fmt(t.matchPoints||0)}</td><td>${fmt(t.boardPoints||0)}</td><td>${t.wins||0}</td></tr>`).join('')}</tbody></table>`
    : `<table><thead><tr><th>Rank</th><th>Player</th><th>Rating</th><th>Points</th>${state.tieBreaks.slice(0,4).map(x=>`<th>${esc(TB_LABELS[x].split(' – ')[0])}</th>`).join('')}</tr></thead><tbody>${st.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(playerDisplay(p))}</td><td>${ratingText(p)}</td><td>${fmt(p.score)}</td>${state.tieBreaks.slice(0,4).map(x=>`<td>${fmt(p[x]||0)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  <h3 style="margin-top:22px">Round-by-Round Results</h3>${roundsHtml||'<p>No rounds yet.</p>'}
  <p style="margin-top:28px;font-size:12px">Generated by Chess Tournament Manager • Concept and Program Design by John Vincent A. Averia</p>`;
}
function exportData(){
  syncSettings();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});
  const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.settings.name||'tournament').replace(/[^a-z0-9]+/gi,'_')+'.json';a.click();URL.revokeObjectURL(a.href);
}
function importData(e){
  const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.settings||!Array.isArray(x.players))throw 0;state=x;ensureTieBreakState();persist();hydrateInputs();renderAll();renderModeTieBreakSelectors();updateTieBreakVisibility();alert('Tournament imported.');}catch(_){alert('Invalid tournament backup file.');}};r.readAsText(f);e.target.value='';
}
function exportStandingsCSV(){
  const st=standings(), headers=['Rank','Player','Delegation','School ID','School','Town/City','Division','Region','Rating','Points',...state.tieBreaks.map(x=>TB_LABELS[x])];
  const rows=[headers,...st.map((p,i)=>[i+1,p.name,delegationLabel(p),p.schoolId||'',p.school||'',p.town||'',p.division||'',p.region||'',ratingText(p),p.score,...state.tieBreaks.map(x=>p[x]||0)])];
  const csv=rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n');
  const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='standings.csv';a.click();URL.revokeObjectURL(a.href);
}
async function resetTournament(){
  if(!state.settings?.tournamentStarted){
    state=defaultState();
    clearUndoHistory();
    hydrateInputs();renderAll();renderTournamentSwitcher();
    showHomeScreen();
    return;
  }

  const id=state.settings.tournamentId;
  const cat=state.settings.tournamentCategory||'current tournament';
  if(!await appConfirm(`Reset only "${cat}"? Other saved tournaments will not be affected.`,{title:'Reset Tournament',confirmText:'Reset'}))return;

  const ws=getMeetWorkspace();
  if(id && ws.tournaments[id])delete ws.tournaments[id];
  if(ws.activeTournamentId===id)ws.activeTournamentId=null;
  saveMeetWorkspace(ws);

  state=defaultState();
  clearUndoHistory();
  safeStorage.setItem('chessManagerAveria',JSON.stringify(state));
  hydrateInputs();
  renderAll();
  renderModeTieBreakSelectors();
  updateTieBreakVisibility();
  renderSavedTournaments();
  renderTournamentSwitcher();
  showHomeScreen();
}
async function loadSample(){
  if(state.players.length||state.rounds.length){if(!await appConfirm('Replace the current tournament with sample data?',{title:'Load Sample',confirmText:'Replace'}))return;}
  state=defaultState();
  state.settings.name='Batangas School Chess Festival - Sample';
  const names=[
    ['Miguel Santos',1620,'Grade 11-A'],['Andrea Reyes',1580,'Grade 11-B'],['Joshua Mendoza',1510,'Grade 10-A'],['Sofia Garcia',1495,'Grade 9-A'],
    ['Nathan Cruz',1450,'Grade 11-A'],['Princess Flores',1400,'Grade 10-B'],['Carlo Bautista',1380,'Grade 9-B'],['Angela Ramos',1365,'Grade 11-C'],
    ['James Aquino',1320,'Grade 10-A'],['Faith Navarro',1280,'Grade 9-A'],['Daniel Castillo',1250,'Grade 8-A'],['Chloe Villanueva',1210,'Grade 8-B']
  ];
  const demoSchools=[
    ['108661','San Pablo Suha ES','Catanauan','Quezon','Region IV-A'],
    ['108649','Catanauan CS','Catanauan','Quezon','Region IV-A'],
    ['108645','Bolo Elementary School','Catanauan','Quezon','Region IV-A'],
    ['108647','Bulagsong ES','Catanauan','Quezon','Region IV-A']
  ];
  state.players=names.map((x,i)=>{
    const s=demoSchools[i%demoSchools.length];
    const parts=x[0].trim().split(/\s+/);
    const last=parts.pop()||'';
    const first=parts.join(' ');
    return {id:uid(),lastName:last,firstName:first,middleInitial:'',name:formatStructuredName(last,first,''),rating:x[1],unrated:false,schoolId:s[0],school:s[1],town:s[2],division:s[3],region:s[4],team:'',category:'Open'};
  });
  // Generate and simulate 3 rounds
  for(let rr=0;rr<3;rr++){
    const games=swissPair(state.players);games.forEach((g,i)=>{if(!g.bye)g.result=['1-0','½-½','0-1','1-0'][i%4];});
    state.rounds.push({number:rr+1,games});
  }
  state.settings.mode='swiss';
  state.settings.swissVariant='flexible';
  state.settings.tournamentStarted=true;
  state.settings.tournamentCategory='Open Sample';
  state.settings.tournamentId=newTournamentId();
  state.settings.updatedAt=new Date().toISOString();
  state.tieBreaksByMode.swiss=cloneDefaultTB('swiss');
  state.tieBreaks=[...state.tieBreaksByMode.swiss];
  persist();hydrateInputs();renderAll();renderModeTieBreakSelectors();updateTieBreakVisibility();goTab('dashboard');
}
